name: Build ETH3D Multi-View Evaluation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: # Enables manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake g++ libpcl-dev libboost-all-dev

    - name: Configure Build
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=bin ..

    - name: Build Project
      run: |
        cd build
        make -j$(nproc)

    - name: List Build Output
      run: |
        echo "Listing build output..."
        ls -R build/bin

    - name: Run Executable (Optional)
      run: |
        echo "Running the built executable..."
        ./build/bin/ETH3DMultiViewEvaluation || echo "Execution failed"
        
    # Add this step to commit the build output to the repository
    - name: Commit and Push Build Output
      run: |
        cd build
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add bin/ # Add the output files
        git commit -m "Add build output" || echo "No changes to commit"
        git push origin main # Push to your repository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
